# Generated by Django 4.1.6 on 2023-02-07 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variacao',
            name='variacao_nome',
        ),
        migrations.AddField(
            model_name='variacao',
            name='estoque',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='variacao',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variacao',
            name='preco',
            field=models.FloatField(default=None, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='variacao',
            name='preco_promocionmal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='variacao',
            name='produto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='produto.produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao_curta',
            field=models.TextField(max_length=255, verbose_name='Descrição curta'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao_longa',
            field=models.TextField(verbose_name='Descrição longa'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_marketing',
            field=models.FloatField(verbose_name='Preço marketing'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_marketing_promocional',
            field=models.FloatField(default=0, verbose_name='Preço marketing promocional'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='produto_nome',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
    ]
