# Generated by Django 4.1.6 on 2023-02-08 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_remove_variacao_variacao_nome_variacao_estoque_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Variação', 'verbose_name_plural': 'Variações'},
        ),
    ]
