# Generated by Django 4.1.6 on 2023-02-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_alter_produto_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variacao',
            old_name='preco_promocionmal',
            new_name='preco_promocional',
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_marketing',
            field=models.FloatField(verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_marketing_promocional',
            field=models.FloatField(default=0, verbose_name='Preço promo'),
        ),
    ]
