# Generated by Django 4.1.6 on 2023-02-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('A', 'Aprovado'), ('C', 'Criado'), ('R', 'Reprovado'), ('P', 'Pendente'), ('E', 'Enviado'), ('F', 'Finalizado')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.FloatField(),
        ),
    ]
