# Generated by Django 4.1.6 on 2023-02-10 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_pedido_qtd_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempedido',
            old_name='quantidae',
            new_name='quantidade',
        ),
    ]
